[tox]
envlist = py311, lint
isolated_build = true

[testenv]
description = test linter
basepython = python3.11
deps =
    pytest
commands =
    pytest

[testenv:lint]
description = Linter-Checks ausführen
basepython = python3.11
skip_install = true
deps =
    ruff
commands =
    ruff check
    ruff format

